spring:
  config:
    import: classpath:common.yml

  datasource:
    username: 'avnadmin'
    url: jdbc:mysql://myportfolio-my-portfolio.a.aivencloud.com:18751/core
    password: 'AVNS_cs8aE3TK20w-bQLF6vk'

  jpa:
    properties:
      hibernate:
        ##### START CACHE CONFIGURATIONS #####
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            fallback: true
            config: redisson-dev-remote.yaml
        #####  END CACHE CONFIGURATIONS  #####

eureka:
  client:
    service-url:
      defaultZone: http://ourlists.ddns.net:8761/eureka
    fetch-registry: true
    register-with-eureka: true