spring:
  config:
    import: classpath:common.yml

  datasource:
    username: 'myportfolio'
    url: jdbc:mysql://mysql:33061/core
    password: 'password'

  jpa:
    properties:
      hibernate:
        ##### START CACHE CONFIGURATIONS #####
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            fallback: true
            config: redisson-dev-docker.yaml
        #####  END CACHE CONFIGURATIONS  #####

eureka:
  client:
    enabled: false