spring:
  config:
    import: classpath:common.yml
  datasource:
    username: 'root'
    url: jdbc:mysql://ourlists.ddns.net:33061/core
    password: 'root_password'
  zipkin:
    base-url: http://ourlists.ddns.net:9411
  jpa:
    properties:
      hibernate:
        ##### START CACHE CONFIGURATIONS #####
        cache:
          use_query_cache: true
          use_second_level_cache: true
          factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            fallback: true
            config: redisson-dev-remote.yaml
        #####  END CACHE CONFIGURATIONS  #####

eureka:
  client:
    service-url:
      defaultZone: http://ourlists.ddns.net:8761/eureka
    fetch-registry: true
    register-with-eureka: true