server:
  port: 8080

core-module-basic-path: "api/core"
scheduled-cron-expression:
  cache-eviction: "0 0 0 * * ?" # Every day at midnight
  #cache-eviction: "0 * * ? * *" # Every minute (Only for tests)

spring:
  application:
    name: core
  jpa:
    # Setting the hibernate dialect is not needed anymore
    #properties:
    #  hibernate:
    #    dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        Cache: TRACE
        type: TRACE
        orm:
          jdbc:
            bind: TRACE