server:
  port: 8080

core-module-basic-path: "api/core"
scheduled-cron-expression:
  cache-eviction: "0 0 0 * * ?" # Every day at midnight
  #cache-eviction: "0 * * ? * *" # Every minute (Only for tests)

spring:
  application:
    name: core
  jpa:
    # Setting the hibernate dialect is not needed anymore
    #properties:
    #  hibernate:
    #    dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  mail:
    host: smtp.gmail.com
    port: 587
    username: dellantonio47@gmail.com
    password: "pqqzctjlfkitskmb" #TODO: Consider using a vault for storing secrets
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        Cache: TRACE
        type: TRACE
        orm:
          jdbc:
            bind: TRACE

google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    secret: 6LcN4hkpAAAAADud5_Q7jkx8bQ2EeTf5eLKdDClC