# TO LAUNCH: docker compose -f docker-compose-dev.yml up -d
version: "3"

services:

  mysql:
    container_name: mysql
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_USER: 'myportfolio'
      MYSQL_PASS: 'password'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - mysql

  eureka-server:
    image: rob097/eureka-server:dev
    container_name: my-eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-dev
    networks:
      - spring-external
      - spring-internal

  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "6379:6379"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-dev
    networks:
      - spring-internal
      - spring-external

  ########################################################################################################################

  apigw:
    image: rob097/apigw:dev
    container_name: myapigw
    ports:
      - "8443:8443"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-dev
    networks:
      - spring-external
      - spring-internal
    depends_on:
      - eureka-server

  auth-service:
    image: rob097/auth-service:dev
    container_name: auth-service
    #Ports removed to not expose the container to the public network. Only ApiGW accessible.
    #ports:
    #  - "9004:9004"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-dev
    networks:
      - spring-internal
      - mysql
    depends_on:
      - mysql
      - eureka-server

  core:
    image: rob097/core:dev
    container_name: core
    #Ports removed to not expose the container to the public network. Only ApiGW accessible.
    #ports:
    #  - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker-dev
    networks:
      - spring-internal
      - mysql
    depends_on:
      - mysql
      - eureka-server

networks:
  mysql:
    driver: bridge
  spring-internal:
    driver: bridge
    internal: true
  spring-external:
    driver: bridge

volumes:
  mysql:
