spring:
  config:
    import: classpath:common.yml
  datasource:
    username: 'myportfolio'
    url: jdbc:mysql://ourlists.ddns.net:33061/auth
    password: 'password'
  #zipkin:
  #  base-url: http://ourlists.ddns.net:9411

eureka:
  client:
    service-url:
      defaultZone: http://ourlists.ddns.net:8761/eureka
    fetch-registry: true
    register-with-eureka: true