server:
  port: 9004

auth-module-basic-path: "api/auth"

spring:
  application:
    name: auth-service
  jpa:
    # Setting the hibernate dialect is not needed anymore
    #properties:
    #  hibernate:
    #    dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        Cache: TRACE
        type: TRACE
        orm:
          jdbc:
            bind: TRACE