spring:
  config:
    import: classpath:common.yml
  datasource:
    username: 'myportfolio'
    url: jdbc:mysql://mysql:3306/auth
    password: 'password'
  zipkin:
    base-url: http://myzipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://my-eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true