server:
  port: 9004

auth-module-basic-path: "api/auth"

spring:
  application:
    name: auth-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE