package com.myprojects.myportfolio.core.configAndUtils;


import com.myprojects.myportfolio.core.dao.BaseDao;
import org.hibernate.HibernateException;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

import java.io.Serializable;

/**
 * Custom ID generator. It allows to override an autogenerated ID if id is present. Otherwise, it generates a new ID.
 * Used In BaseDao.
 */
@SuppressWarnings("unused")
public class UseExistingIdOtherwiseGenerateUsingIdentity extends SequenceStyleGenerator {

    @Override
    public Serializable generate(SharedSessionContractImplementor session, Object object) throws HibernateException {
        if (object instanceof BaseDao identifiable) {
            if (identifiable.getId() != null && identifiable.getId() != 0) {
                return identifiable.getId();
            }
        }

        return (Integer) super.generate(session, object);

    }
}
