server:
  ssl:
    enabled: true
    key-store: classpath:springboot.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: springboot
    key-password: password
  port: 8443

spring:
  config:
    import: classpath:common.yml
  cloud:
    config:
      discovery:
        enabled: false

eureka:
  client:
    enabled: false

clients:
  routing-prefix: "http://"
  auth:
    name: auth-service:9004
    path: /api/auth
  core:
    name: core:8080
    path: /api/core