server:
  ssl:
    enabled: false
  port: 8443

spring:
  config:
    import: classpath:common.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

clients:
  routing-prefix: "lb://"
  auth:
    name: AUTH-SERVICE
    path: /api/auth
  core:
    name: CORE
    path: /api/core