server:
  ssl:
    enabled: true
    key-store: classpath:springboot.jks
    key-store-password: password
    key-store-type: JKS
    key-alias: springboot
    key-password: password
  port: 8443

spring:
  config:
    import: classpath:common.yml