spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
              - PUT
              - DELETE
            allowedHeaders: "*"
            exposedHeaders:
              - "IS-EMPTY"
              - "IS-LAST"
              - "NUMBER"

clients:
  auth:
    name: AUTH-SERVICE
    path: /api/auth
  core:
    name: CORE
    path: /api/core